In [143]:
import numpy as np
import pandas as pd

## Matrix Info

In [144]:
data = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [145]:
data = np.array(data)

In [146]:
data.dtype

dtype('int32')

In [147]:
data.size

9

In [148]:
data.shape

(3, 3)

## Create New Matrix

In [149]:
np.empty((3,3))

array([[  2.71828183e+00,   7.38905610e+00,   2.00855369e+01],
       [  5.45981500e+01,   1.48413159e+02,   4.03428793e+02],
       [  1.09663316e+03,   2.98095799e+03,   8.10308393e+03]])

In [150]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [151]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [152]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [153]:
np.arange(15).reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Random

In [154]:
np.random.randn(3,5)

array([[-0.00760603,  0.38776906,  0.94813415,  1.26968149, -0.25805032],
       [-0.38190284,  1.94829326,  0.99023458,  0.90738618, -0.92741304],
       [ 2.3498184 , -0.09040285, -0.53497519,  0.42574174, -0.89243658]])

In [193]:
np.random.normal(size=(4,4))

array([[ -1.22312051e+00,   1.53270078e-03,   2.51724729e+00,
          1.37939610e+00],
       [ -1.84473047e+00,  -1.39273546e+00,   5.70214857e-01,
          7.43251437e-01],
       [ -7.03894273e-01,  -5.79065837e-01,   1.24448602e+00,
          7.26377813e-01],
       [ -9.22980118e-01,   1.37060052e+00,   7.65130555e-01,
          2.46592484e-01]])

In [194]:
%timeit np.random.normal(size=100000)

5.72 ms ± 7.76 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [195]:
np.random.rand(10)

array([ 0.06774488,  0.86012116,  0.79608192,  0.0942477 ,  0.76627957,
        0.69416193,  0.78920294,  0.852636  ,  0.68300131,  0.02774046])

In [199]:
np.random.randint(1,10,size=(3,3))

array([[4, 1, 4],
       [3, 1, 4],
       [9, 8, 8]])

In [215]:
np.random.binomial(n = 10, p = 0.3,size=10)

array([4, 6, 1, 6, 3, 5, 5, 3, 3, 4])

## Type Conversion

In [155]:
data.astype(np.float32)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

## Operation

In [156]:
data * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [157]:
data + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [158]:
np.exp(data)

array([[  2.71828183e+00,   7.38905610e+00,   2.00855369e+01],
       [  5.45981500e+01,   1.48413159e+02,   4.03428793e+02],
       [  1.09663316e+03,   2.98095799e+03,   8.10308393e+03]])

## Slicing

In [159]:
data[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [160]:
data[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [161]:
temp = data.copy()
temp[1:3, 1:3] = 10
temp

array([[ 1,  2,  3],
       [ 4, 10, 10],
       [ 7, 10, 10]])

In [162]:
# Bolean Indexing
mask = data>5
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [163]:
data[mask]

array([6, 7, 8, 9])

In [164]:
data[[2,1,0], :]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [165]:
data[:, [2,1,0]]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

## Transpose

In [166]:
data.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [167]:
np.where(data>5, 1, 0)

array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 1]])

## Boolean Array

In [168]:
bools = np.array([True, False, False, False])

In [169]:
bools.any()

True

In [170]:
bools.all()

False

## Sort??

In [173]:
data.sort()
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
data.sort(axis=0)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Load and Save

In [177]:
np.save("data", data)

In [178]:
data = np.load("data.npy")

In [179]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Linear Algebra

In [183]:
X = [
    [1,2,3],
    [4,5,6]
]
Y = [
    [6,23],
    [-1,7],
    [8,9]
]
X = np.array(X)
Y = np.array(Y)

In [185]:
X.dot(Y)

array([[ 28,  64],
       [ 67, 181]])